# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordlocator', '0008_auto_20150927_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
