language: python

python:
  - "3.4"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-dev.txt

script:
  - cd ekip
  - coverage run --source=foia_hub manage.py test --settings=foia_hub.settings.test

after_success:
  - coveralls
