language: python

services:
- postgresql

python:
  - "3.6"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-dev.txt

before_script:
  - psql -c "create user ekip with password 'ekip';" -U postgres
  - psql -c "alter user ekip with superuser;" -U postgres
  - psql -c "CREATE DATABASE ekip;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE ekip TO ekip;" -U postgres

script:
  - bandit -r ekip
  - cd ekip
  - coverage run --source=everykid manage.py test --settings=config.settings.test

after_success:
  - coveralls